version: "3.9"

services:
  bot:
    build:
      context: ./bot
      dockerfile: ./Dockerfile
    ports:
      - "8080:8080"
    restart: always
    networks:
      - backend

networks:
  backend: {}