version: "3.9"

services:

  orchestrator:
    build: 
      context: ./orchestrator/
      dockerfile: ./orchestrator/Dockerfile
    networks: 
      - internal
      - orchestrator_backend
    container_name: orchestrator
    command: python -u -m flask run -h 0.0.0.0 -p 5000
    depends_on:
      - test_generator

  runner:
    build: 
      dockerfile: ./orchestrator/runners/Dockerfile
      context: .
    networks: 
      - internal
    command: python -u runner.py run_tests
    depends_on:
      - test_generator

  test_generator:
    build: 
      dockerfile: ./orchestrator/runners/Dockerfile
      context: .
    networks: 
      - internal
    command: python -u runner.py generate
    
  bot:
    build:
      context: ./bot
      dockerfile: ./Dockerfile
    ports:
      - "8080:8080"
    restart: always
    networks:
      - bot_backend

networks:
  internal:
  bot_backend:
  orchestrator_backend:
